service: cpustress-${opt:suffix}

provider:
  name: aws
  project: faastest
  stackName: cpustress-${opt:suffix}
  stage: dev
  versionFunctions: false
  timeout: 20

functions:
  node810-memory-128:
    name: cpustress-node810-128mb-${opt:suffix}
    description: cpu intensive function 128mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 128

  node810-memory-256:
    name: cpustress-node810-256mb-${opt:suffix}
    description: cpu intensive function 256mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 256

  node810-memory-512:
    name: cpustress-node810-512mb-${opt:suffix}
    description: cpu intensive function 512mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 512

  node810-memory-1024:
    name: cpustress-node810-1024mb-${opt:suffix}
    description: cpu intensive function 1024mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 1024

  node810-memory-1536:
    name: cpustress-node810-1536mb-${opt:suffix}
    description: cpu intensive function 1536mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 1536
