service: netstress-${opt:suffix}

provider:
  name: google
  project: faastest
  stackName: netstress-${opt:suffix}
  credentials: /tmp/.gcloud/faasbenchmark.json
  stage: dev

plugins:
  - serverless-google-cloudfunctions
  
functions:
  network-node810-128mb:
    name: --network-node810-128mb-${opt:suffix}
    description: network stress function 128mb
    runtime: nodejs8
    handler: test128
    memorySize: 128
    events:
      - http: path

  network-node810-256mb:
    name: --network-node810-256mb-${opt:suffix}
    description: network stress function 256mb
    runtime: nodejs8
    handler: test256
    memorySize: 256
    events:
      - http: path

  network-node810-512mb:
    name: --network-node810-512mb-${opt:suffix}
    description: network stress function 512mb
    runtime: nodejs8
    handler: test512
    memorySize: 512
    events:
      - http: path

  network-node810-1024mb:
    name: --network-node810-1024mb-${opt:suffix}
    description: network stress function 1024mb
    runtime: nodejs8
    handler: test1024
    memorySize: 1024
    events:
      - http: path

  network-node810-2048mb:
    name: --network-node810-2048mb-${opt:suffix}
    description: network stress function 2048mb
    runtime: nodejs8
    handler: test2048
    memorySize: 2048
    events:
      - http: path
