service: sleepfunc-${opt:suffix}

package:
  individually: true
  exclude:
  - csharp/**
  - java8/**
  - python/**
  - nodejs/**
  - golang/**

provider:
  name: aws
  project: faastest
  stackName: sleepfunc-${opt:suffix}
  stage: dev
  versionFunctions: false
  timeout: 20

functions:
  node12-memory-128:
    package:
      include:
      - nodejs/**
    name: sleep-node12-128mb
    description: sleep function 128mb
    runtime: nodejs12.x
    handler: nodejs/handler.hello
    memorySize: 128

  node12-memory-256:
    package:
      include:
        - nodejs/**
    name: sleep-node12-256mb
    description: sleep function 256mb
    runtime: nodejs12.x
    handler: nodejs/handler.hello
    memorySize: 256

  node12-memory-512:
    package:
      include:
        - nodejs/**
    name: sleep-node12-512mb
    description: sleep function 512mb
    runtime: nodejs12.x
    handler: nodejs/handler.hello
    memorySize: 512

  node12-memory-1024:
    package:
      include:
        - nodejs/**
    name: sleep-node12-1024mb
    description: sleep function 1024mb
    runtime: nodejs12.x
    handler: nodejs/handler.hello
    memorySize: 1024

  node12-memory-1536:
    package:
      include:
        - nodejs/**
    name: sleep-node12-1536mb
    description: sleep function 1536mb
    runtime: nodejs12.x
    handler: nodejs/handler.hello
    memorySize: 1536

  java8-memory-128:
    package:
      artifact: java8/target/hello-dev.jar
    name: sleep-java8-128mb-${opt:suffix}
    description: sleep function 128mb
    runtime: java8
    handler: com.serverless.Handler
    memorySize: 128

  java8-memory-256:
    package:
      artifact: java8/target/hello-dev.jar
    name: sleep-java8-256mb-${opt:suffix}
    description: sleep function 256mb
    runtime: java8
    handler: com.serverless.Handler
    memorySize: 256

  java8-memory-512:
    package:
      artifact: java8/target/hello-dev.jar
    name: sleep-java8-512mb-${opt:suffix}
    description: sleep function 512mb
    runtime: java8
    handler: com.serverless.Handler
    memorySize: 512

  java8-memory-1024:
    package:
      artifact: java8/target/hello-dev.jar
    name: sleep-java8-1024mb-${opt:suffix}
    description: sleep function 1024mb
    runtime: java8
    handler: com.serverless.Handler
    memorySize: 1024

  java8-memory-1536:
    package:
      artifact: java8/target/hello-dev.jar
    name: sleep-java8-1536mb-${opt:suffix}
    description: sleep function 1536mb
    runtime: java8
    handler: com.serverless.Handler
    memorySize: 1536

  java11-memory-128:
    package:
      artifact: java11/target/hello-dev.jar
    name: sleep-java11-128mb
    description: sleep function 128mb
    runtime: java11
    handler: com.serverless.Handler
    memorySize: 128

  java11-memory-256:
    package:
      artifact: java11/target/hello-dev.jar
    name: sleep-java11-256mb
    description: sleep function 256mb
    runtime: java11
    handler: com.serverless.Handler
    memorySize: 256

  java11-memory-512:
    package:
      artifact: java11/target/hello-dev.jar
    name: sleep-java11-512mb
    description: sleep function 512mb
    runtime: java11
    handler: com.serverless.Handler
    memorySize: 512

  java11-memory-1024:
    package:
      artifact: java11/target/hello-dev.jar
    name: sleep-java11-1024mb
    description: sleep function 1024mb
    runtime: java11
    handler: com.serverless.Handler
    memorySize: 1024

  java11-memory-1536:
    package:
      artifact: java11/target/hello-dev.jar
    name: sleep-java11-1536mb
    description: sleep function 1536mb
    runtime: java11
    handler: com.serverless.Handler
    memorySize: 1536

  dotnetcore21-memory-128:
    package:
      artifact: csharp/deploy.zip
    name: sleep-dotnetcore21-128mb-${opt:suffix}
    description: sleep function 128mb
    runtime: dotnetcore2.1
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    memorySize: 128

  dotnetcore21-memory-256:
    package:
      artifact: csharp/deploy.zip
    name: sleep-dotnetcore21-256mb-${opt:suffix}
    description: sleep function 256mb
    runtime: dotnetcore2.1
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    memorySize: 256

  dotnetcore21-memory-512:
    package:
      artifact: csharp/deploy.zip
    name: sleep-dotnetcore21-512mb-${opt:suffix}
    description: sleep function 512mb
    runtime: dotnetcore2.1
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    memorySize: 512

  dotnetcore21-memory-1024:
    package:
      artifact: csharp/deploy.zip
    name: sleep-dotnetcore21-1024mb-${opt:suffix}
    description: sleep function 1024mb
    runtime: dotnetcore2.1
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    memorySize: 1024

  dotnetcore21-memory-1536:
    package:
      artifact: csharp/deploy.zip
    name: sleep-dotnetcore21-1536mb-${opt:suffix}
    description: sleep function 1536mb
    runtime: dotnetcore2.1
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello
    memorySize: 1536

  python38-memory-128:
    package:
      include:
        - python/**
    name: sleep-python38-128mb
    description: sleep function 128mb
    runtime: python3.8
    handler: python/handler.hello
    memorySize: 128

  python38-memory-256:
    package:
      include:
        - python/**
    name: sleep-python38-256mb
    description: sleep function 256mb
    runtime: python3.8
    handler: python/handler.hello
    memorySize: 256

  python38-memory-512:
    package:
      include:
        - python/**
    name: sleep-python38-512mb
    description: sleep function 512mb
    runtime: python3.8
    handler: python/handler.hello
    memorySize: 512

  python38-memory-1024:
    package:
      include:
        - python/**
    name: sleep-python38-1024mb
    description: sleep function 1024mb
    runtime: python3.8
    handler: python/handler.hello
    memorySize: 1024

  python38-memory-1536:
    package:
      include:
        - python/**
    name: sleep-python38-1536mb
    description: sleep function 1536mb
    runtime: python3.8
    handler: python/handler.hello
    memorySize: 1536

  python37-memory-128:
    package:
      include:
        - python/**
    name: sleep-python37-128mb-${opt:suffix}
    description: sleep function 128mb
    runtime: python3.7
    handler: python/handler.hello
    memorySize: 128

  python37-memory-256:
    package:
      include:
        - python/**
    name: sleep-python37-256mb-${opt:suffix}
    description: sleep function 256mb
    runtime: python3.7
    handler: python/handler.hello
    memorySize: 256

  python37-memory-512:
    package:
      include:
        - python/**
    name: sleep-python37-512mb-${opt:suffix}
    description: sleep function 512mb
    runtime: python3.7
    handler: python/handler.hello
    memorySize: 512

  python37-memory-1024:
    package:
      include:
        - python/**
    name: sleep-python37-1024mb-${opt:suffix}
    description: sleep function 1024mb
    runtime: python3.7
    handler: python/handler.hello
    memorySize: 1024

  python37-memory-1536:
    package:
      include:
        - python/**
    name: sleep-python37-1536mb-${opt:suffix}
    description: sleep function 1536mb
    runtime: python3.7
    handler: python/handler.hello
    memorySize: 1536

  golang-memory-128:
    package:
      include:
        - golang/**
    name: sleep-golang-128mb-${opt:suffix}
    description: sleep function 128mb
    runtime: go1.x
    handler: golang/bin/hello
    memorySize: 128

  golang-memory-256:
    package:
      include:
        - golang/**
    name: sleep-golang-256mb-${opt:suffix}
    description: sleep function 256mb
    runtime: go1.x
    handler: golang/bin/hello
    memorySize: 256

  golang-memory-512:
    package:
      include:
        - golang/**
    name: sleep-golang-512mb-${opt:suffix}
    description: sleep function 512mb
    runtime: go1.x
    handler: golang/bin/hello
    memorySize: 512

  golang-memory-1024:
    package:
      include:
        - golang/**
    name: sleep-golang-1024mb-${opt:suffix}
    description: sleep function 1024mb
    runtime: go1.x
    handler: golang/bin/hello
    memorySize: 1024

  golang-memory-1536:
    package:
      include:
        - golang/**
    name: sleep-golang-1536mb-${opt:suffix}
    description: sleep function 1536mb
    runtime: go1.x
    handler: golang/bin/hello
    memorySize: 1536
