service: providerstorage-${opt:suffix}

provider:
  name: google
  project: faastest
  stackName: providerstorage-${opt:suffix}
  credentials: /tmp/.gcloud/faasbenchmark.json
  stage: dev

plugins:
  - serverless-google-cloudfunctions
  - serverless-gbucket-remover
  
functions:
  provider-storage-node810-128mb:
    name: --provider-storage-node810-128mb-${opt:suffix}
    description: provider storage function 128mb
    runtime: nodejs8
    handler: test128
    memorySize: 128
    events:
      - http: path

  provider-storage-node810-256mb:
    name: --provider-storage-node810-256mb-${opt:suffix}
    description: provider storage function 256mb
    runtime: nodejs8
    handler: test256
    memorySize: 256
    events:
      - http: path

  provider-storage-node810-512mb:
    name: --provider-storage-node810-512mb-${opt:suffix}
    description: provider storage function 512mb
    runtime: nodejs8
    handler: test512
    memorySize: 512
    events:
      - http: path

  provider-storage-node810-1024mb:
    name: --provider-storage-node810-1024mb-${opt:suffix}
    description: provider storage function 1024mb
    runtime: nodejs8
    handler: test1024
    memorySize: 1024
    events:
      - http: path

  provider-storage-node810-2048mb:
    name: --provider-storage-node810-2048mb-${opt:suffix}
    description: provider storage function 2048mb
    runtime: nodejs8
    handler: test2048
    memorySize: 2048
    events:
      - http: path

resources:
  resources:
  - type: storage.v1.bucket
    name: nwbfaastest1337
    properties:
      project: faastest
      name: nwbfaastest1337

custom:
  remover:
    buckets:
    - nwbfaastest1337
