service: memstress

provider:
  name: google
  project: faastest
  credentials: /tmp/.gcloud/faasbenchmark.json
  stage: dev

plugins:
  - serverless-google-cloudfunctions
  
functions:
  memory-node810-128mb:
    name: --memory-node810-128mb
    description: memory stress function 128mb
    runtime: nodejs8
    handler: test128
    memorySize: 128
    events:
      - http: path

  memory-node810-256mb:
    name: --memory-node810-256mb
    description: memory stress function 256mb
    runtime: nodejs8
    handler: test256
    memorySize: 256
    events:
      - http: path

  memory-node810-512mb:
    name: --memory-node810-512mb
    description: memory stress function 512mb
    runtime: nodejs8
    handler: test512
    memorySize: 512
    events:
      - http: path

  memory-node810-1024mb:
    name: --memory-node810-1024mb
    description: memory stress function 1024mb
    runtime: nodejs8
    handler: test1024
    memorySize: 1024
    events:
      - http: path

  memory-node810-2048mb:
    name: --memory-node810-2048mb
    description: memory stress function 2048mb
    runtime: nodejs8
    handler: test2048
    memorySize: 2048
    events:
      - http: path
