service: providerstorage-${opt:suffix}

provider:
  name: aws
  stackName: providerstorage-${opt:suffix}
  project: faastest
  stage: dev
  versionFunctions: false
  timeout: 20
  environment:
    TEST_BUCKET: nwbfaastest
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

plugins:
  - serverless-s3-remover

functions:
  node810-memory-128:
    name: providerstorage-node810-128mb-${opt:suffix}
    description: upload a file to s3 128mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 128

  node810-memory-256:
    name: providerstorage-node810-256mb-${opt:suffix}
    description: upload a file to s3 256mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 256

  node810-memory-512:
    name: providerstorage-node810-512mb-${opt:suffix}
    description: upload a file to s3 512mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 512

  node810-memory-1024:
    name: providerstorage-node810-1024mb-${opt:suffix}
    description: upload a file to s3 1024mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 1024

  node810-memory-1536:
    name: providerstorage-node810-1536mb
    description: upload a file to s3 1536mb
    runtime: nodejs8.10
    handler: nodejs/handler.handler
    memorySize: 1536

resources:
  Resources:
    S3BucketNwbfaastest:
      Type: 'AWS::S3::Bucket'
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:provider.environment.TEST_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

custom:
  remover:
    buckets:
      - ${self:provider.environment.TEST_BUCKET}

